const mongoose = require('mongoose')
const { Schema } = mongoose;
const CompYachtPlanSchema = new Schema({
    line_of_business_id: { type: Schema.Types.ObjectId, ref: 'line_of_businesses' },
    plan_name: { type: String },
    company_id: { type: Schema.Types.ObjectId, ref: 'companies' },
    plan_category_id: { type: Schema.Types.ObjectId, ref: 'plan_categories' },
    nature_of_plan_id: { type: Schema.Types.ObjectId, ref: 'nature_of_plans' },
    policy_type_id: { type: Schema.Types.ObjectId, ref: 'policy_types' },
    plan_for: { type: Array },
    business_type: { type: Array },
    initial_rate: { type: String },
    discount_rate: { type: String },
    rate: { type: String },
    excess: { type: String },
    yacht_body_type_or_topup: { type: Array },
    yacht_hull_material_or_topup: { type: Array },
    yacht_horsepower_type_or_topup: { type: Array },
    yacht_engine_type_or_topup: { type: Array },
    measurement_value_or_topup: { type: Array },
    yacht_breadth_value_or_topup: { type: Array },
    yacht_speed_knot_type_or_topup: { type: Array },
    driving_experience_or_topup: { type: Array },
    home_country_driving_experience_or_topup: { type: Array },
    hull_and_equipment_value_range_or_topup: { type: Array },
    dinghy_ten_value_range_or_topup: { type: Array },
    outboard_value_range_or_topup: { type: Array },
    personal_eff_cash_or_topup: { type: Array },
    trailer_or_topup: { type: Array },
    no_claim_years: { type: Array },
    passenger_capacity_or_topup: { type: Array },
    last_year_policy_type_or_topup: { type: Array },
    age_of_the_car_or_topup: { type: Array },
    crew_capacity_or_topup: { type: Array },
    add_op_con_desc_or_topup: { type: Array },
    jdv_commission: { type: String },
    status: { type: Number, default: 1 },
    standard_cover_arr: { type: Array },
    additional_cover_arr: { type: Array },
    condition_arr: { type: Array },
    location: { type: Array },
    policywordings_file: { type: [String], default: [] },
    black_listed_Yacht: { type: Array },
    plan_created_by: { type: mongoose.Types.ObjectId }
});
module.exports = mongoose.model('yacht_plan', CompYachtPlanSchema)